version: '3.8'

services:
  web:
    build: .
    container_name: flask_app
    command: flask run --host=0.0.0.0
    ports:
      - "5000:5000"
    environment:
      FLASK_ENV: development
      FLASK_APP: main.py
      DATABASE_URI: mysql+pymysql://root:password@db/flask_db
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: flask_db
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: flask_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: